[package]
name = "topology"
version.workspace = true
edition.workspace = true

[dependencies]
cluster-types = { path = "../cluster-types" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
